export const CREATE_TODO = "CREATE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";


export const FETCH_TODO_RESULTS = "FETCH_TODO_RESULT";
export const FETCH_TODO_ERROR = "FETCH_TODO_ERROR"